# This workflow triggers on pull requests that modify files in the web module (i.e., apps/web/**)
# It runs component and end-to-end (E2E) tests to validate changes.

name: PR CI for Web module

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - "apps/web/**"
      - "!apps/web/**/*.md"
  workflow_dispatch:

jobs:
  component-e2e-tests:
    runs-on: ubuntu-latest
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      NEXT_PUBLIC_WALLET_APP_API: ${{ vars.NEXT_PUBLIC_WALLET_APP_API }}
      NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
      NEXT_PUBLIC_API_TIMEOUT: ${{ vars.NEXT_PUBLIC_API_TIMEOUT }}
      NEXT_PUBLIC_API_RETRIES: ${{ vars.NEXT_PUBLIC_API_RETRIES }}
      NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
      CORS_ORIGINS_DEV: ${{ vars.CORS_ORIGINS_DEV }}
      PRIVATE_KEYCLOAK_REALM: ${{ secrets.PRIVATE_KEYCLOAK_REALM }}
      PRIVATE_KEYCLOAK_BASE_URL: ${{ secrets.PRIVATE_KEYCLOAK_BASE_URL }}
      PRIVATE_KEYCLOAK_CLIENT_SECRET: ${{ secrets.PRIVATE_KEYCLOAK_CLIENT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PRIVATE_KEYCLOAK_CLIENT_ID: ${{ secrets.PRIVATE_KEYCLOAK_CLIENT_ID }}
      PRIVATE_WALLET_API_KEY: ${{ secrets.PRIVATE_WALLET_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Start user service in the background
        run: yarn user:dev &>/dev/null & npx wait-on tcp:8080 --timeout 30000

      - name: Run component test
        uses: cypress-io/github-action@v6
        with:
          command: yarn cypress-component-test && yarn cypress-e2e-headless-test
